### ISSUE TITLE
Frequent crash on Vivaldi Browser

### ISSUE THREAD

**Issue by 66Leo66** [JingMatrix/ChromeXt#152]
I'm on latest CI version of ChromeXt and latest Play Store version of Vivaldi(Vivaldi 6.5.3217.122).

I'm not sure if stack trace is useful or not, attached below. Tell me if any additional information is required.

It's happening 5~10 times a day.
```
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Redmi
[Device Model]: 22011211C
[Display]: UP1A.231005.007
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 4728
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.vivaldi.browser
[Version Name]: 6.5.3217.122
[Version Code]: 532170122
[Target SDK]: 34
[Min SDK]: 26
[Error Type]: JVM
[Crash Time]: 2024-02-24T11:07:58.761
[Stack Trace]:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at q.h.a(SourceFile:97)
	at n.a.run(SourceFile:140)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8706)
	... 3 more
Caused by: java.lang.RuntimeException: Tab.loadUrl called on a destroyed tab
	at org.chromium.chrome.browser.tab.TabImpl.j(chromium-Vivaldi.6.5.3217.122.apk-stable-532170122:162)
	... 11 more
```

**Comment by 66Leo66** [comment]
BTW: Since maybe one update of vivaldi browser, neither KISS translator nor Immersive translate works. They are installed and visible from ChromeXt management frontend, but not showing any floating button and not functioning. KISS translator settings frontend is not detecting an installtion.

Another self-made simple dom manuplating script works fine.

Also, is there a way to check ChromeXt debug log or something?

**Comment by JingMatrix** [comment]
I will check theUserScript issue of Vivaldi later.
Currently, it crashes may be due to your frequent somehow forced close of tabs. It could also be a bug in the code checking if a tab is already closed.
To debug `ChromeXt`, you should install the debug version, for which you need to compile it by yourself. Then you can inspect the logs using the `adb` command, for example
```
adb logcat -s ChromeXt AndroidRunTime LSPosed
```

**Comment by 66Leo66** [comment]
I can confirm they're fixed for me using latest CI build. Thank you very much!
