### ISSUE TITLE
Crash on Samsung Internet

### ISSUE THREAD

**Issue by ehfkwlfkwl** [JingMatrix/ChromeXt#153]
I'm using the lastest builds of LSPacth and ChromeXt
Works fine with the latest version of Samsung Internet on Play Store (v23.0.1.1)
But crashes on later versions - Samsung Internet on Galaxy Store (v24.0.1.2), Samsung Internet Beta on Play Store (v24.0.3.2), Samsung Internet Beta on Galaxy Store (v25.0.0.20)

APK links
Samsung Internet : https://apkpure.com/kr/samsung-internet-browser/com.sec.android.app.sbrowser/download
Samsung Internet Beta : https://apkpure.com/kr/samsung-internet-browser-beta/com.sec.android.app.sbrowser.beta/download

**Comment by JingMatrix** [comment]
I have made some changes to ChromeXt involving the codes for Samsung browsers (Play Store, beta version) while fixing another bug.
Currently, I cannot reproduce your issue.

Please try the latest ChromeXt **again** to see if the issue persists.

**Comment by ehfkwlfkwl** [comment]
I retried the latest ChromeXt uploaded today and it still crashes.
But I found that it only crashes on my Galaxy S24 plus(Android 14).
When I installed the same apk on Redmi Note 9s(Android 11), it works fine.

**Comment by JingMatrix** [comment]
I am using Android 14, and here is my patched APK: https://file.io/7gQnMoBPyWye

Please try it, because on my Pixel 6 everything works as expected.

**Comment by ehfkwlfkwl** [comment]
Unfortunately, your apk doesn't work too
I think it's because Galaxy S24's AI service on Samsung Internet.

```
03-10 18:30:28.313 20216 20216 I ViewRootImpl@5fde030[SBrowserMainActivity]: synced displayState. AttachInfo displayState=2
03-10 18:30:28.313 20216 20216 I ViewRootImpl@5fde030[SBrowserMainActivity]: setView = com.android.internal.policy.DecorView@b96e9cf TM=true
03-10 18:30:28.313 20216 20216 I ViewRootImpl@b756368[HelpIntroActivity]: handleWindowFocusChanged: 0 0 call from android.view.ViewRootImpl.-$$Nest$mhandleWindowFocusChanged:0
03-10 18:30:28.313 20216 20216 I ImeFocusController: onPreWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
03-10 18:30:28.313 20216 20216 I ImeFocusController: onPostWindowFocus: skipped, hasWindowFocus=false mHasImeFocus=true
03-10 18:30:28.314 20216 20216 I FlexModeUtil: postures = 0
03-10 18:30:28.314 20216 20216 I FlexModeUtil: updateDisplayFeature: WindowLayoutInfo{ DisplayFeatures[] }
03-10 18:30:28.314 20216 20216 I FlexModeUtil: No display features
03-10 18:30:28.314 20216 20216 I SurfaceView@ef195f1: onWindowVisibilityChanged(0) true android.view.SurfaceView{ef195f1 V.E...... ......I. 0,0-0,0} of ViewRootImpl@5fde030[SBrowserMainActivity]
03-10 18:30:28.314 20216 20216 I ScsApi@NeuralTranslator: NeuralTranslator -- refresh() executed
03-10 18:30:28.315 20216 20216 I ScsApi@NeuralTranslator: NeuralTranslator -- getSourceLanguageList() executed
03-10 18:30:28.315 20216 20665 I ScsApi@ServiceExecutor: task >> NeuralTranslationServiceExecutor@67e7b3a >> RefreshNeuralTranslatorRunnable@64253eb
03-10 18:30:28.315 20216 20216 I TextTranslate: update source language list :
03-10 18:30:28.315 20216 20665 I ScsApi@Feature: checkFeature() : FEATURE_NEURAL_TRANSLATION, sdk : 3.1.26
03-10 18:30:28.316 20216 20665 I ScsApi@FeatureHolder: setStatus() : FEATURE_NEURAL_TRANSLATION : 0
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge: Crash unexpectedly: java.lang.SecurityException: Not allowed to bind to service Intent { act=intellivoiceservice.intent.action.BIND_TRANSLATION pkg=com.samsung.android.intellivoiceservice }
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2203)
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at android.app.ContextImpl.bindService(ContextImpl.java:2060)
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at android.content.ContextWrapper.bindService(ContextWrapper.java:878)
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at com.samsung.android.sdk.scs.base.connection.ConnectionManager.connectToService(Unknown Source:52)
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at com.samsung.android.sdk.scs.base.connection.ConnectionManager.connect(Unknown Source:18)
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at com.samsung.android.sdk.scs.base.connection.ServiceExecutor.connect(Unknown Source:19)
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at com.samsung.android.sdk.scs.base.connection.ServiceExecutor.beforeExecute(Unknown Source:97)
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-10 18:30:28.318 20216 20665 I LSPosed-Bridge:        at java.lang.Thread.run(Thread.java:1012)
--------- beginning of crash
03-10 18:30:28.318 20216 20665 E AndroidRuntime: FATAL EXCEPTION: pool-11-thread-1
03-10 18:30:28.318 20216 20665 E AndroidRuntime: Process: com.sec.android.app.sbrowser.beta, PID: 20216
03-10 18:30:28.318 20216 20665 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=intellivoiceservice.intent.action.BIND_TRANSLATION pkg=com.samsung.android.intellivoiceservice }
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2203)
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at android.app.ContextImpl.bindService(ContextImpl.java:2060)
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at android.content.ContextWrapper.bindService(ContextWrapper.java:878)
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ConnectionManager.connectToService(Unknown Source:52)
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ConnectionManager.connect(Unknown Source:18)
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ServiceExecutor.connect(Unknown Source:19)
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ServiceExecutor.beforeExecute(Unknown Source:97)
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-10 18:30:28.318 20216 20665 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
03-10 18:30:28.342 20216 20216 I BLASTBufferQueue_Java: new BLASTBufferQueue, mName= ViewRootImpl@5fde030[SBrowserMainActivity] mNativeObject= 0xb400006fb0ca7a90 sc.mNativeObject= 0xb4000070c0c80010 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3031 android.view.ViewRootImpl.relayoutWindow:10121 android.view.ViewRootImpl.performTraversals:4115 android.view.ViewRootImpl.doTraversal:3291 android.view.ViewRootImpl$TraversalRunnable.run:11329 android.view.Choreographer$CallbackRecord.run:1689 android.view.Choreographer$CallbackRecord.run:1698 android.view.Choreographer.doCallbacks:1153 android.view.Choreographer.doFrame:1079 android.view.Choreographer$FrameDisplayEventReceiver.run:1646
03-10 18:30:28.342 20216 20216 I BLASTBufferQueue_Java: update, w= 1080 h= 2340 mName = ViewRootImpl@5fde030[SBrowserMainActivity] mNativeObject= 0xb400006fb0ca7a90 sc.mNativeObject= 0xb4000070c0c80010 format= -3 caller= android.graphics.BLASTBufferQueue.<init>:89 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:3031 android.view.ViewRootImpl.relayoutWindow:10121 android.view.ViewRootImpl.performTraversals:4115 android.view.ViewRootImpl.doTraversal:3291 android.view.ViewRootImpl$TraversalRunnable.run:11329
03-10 18:30:28.342 20216 20216 I ViewRootImpl@5fde030[SBrowserMainActivity]: Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) relayoutAsync=false req=(1080,2340)0 dur=25 res=0x403 s={true 0xb400007040cfa490} ch=true seqId=0
03-10 18:30:28.343 20216 20216 I ViewRootImpl@5fde030[SBrowserMainActivity]: performConfigurationChange setNightDimText nightDimLevel=0
03-10 18:30:28.343 20216 20304 W vulkan  : CreateSwapchainKHR(VkSwapchainCreateInfoKHR.imageColorSpace = 1000104013) failed: Unsupported color space, but assume as Success for ANGLE.
03-10 18:30:28.344 20216 20216 I si__Toolbar: height changed: top: 0 oldTop: 0 bottom: 135 oldBottom: 0
03-10 18:30:28.344 20216 20216 I SurfaceView@ef195f1: windowStopped(false) true android.view.SurfaceView{ef195f1 V.E...... ......I. 0,0-0,0} of ViewRootImpl@5fde030[SBrowserMainActivity]
03-10 18:30:28.346 20216 20216 I ViewRootImpl@5fde030[SBrowserMainActivity]: Setup new sync=wmsSync-ViewRootImpl@5fde030[SBrowserMainActivity]#2
03-10 18:30:28.346 20216 20216 I ViewRootImpl@5fde030[SBrowserMainActivity]: Creating new active sync group ViewRootImpl@5fde030[SBrowserMainActivity]#3
03-10 18:30:28.346 20216 20216 I ViewRootImpl@5fde030[SBrowserMainActivity]: registerCallbacksForSync syncBuffer=false
03-10 18:30:28.347 20216 20312 I ViewRootImpl@5fde030[SBrowserMainActivity]: Received frameDrawingCallback syncResult=0 frameNum=1.
03-10 18:30:28.347 20216 20312 I ViewRootImpl@5fde030[SBrowserMainActivity]: mWNT: t=0xb400006eb0c92d90 mBlastBufferQueue=0xb400006fb0ca7a90 fn= 1 mRenderHdrSdrRatio=1.0 caller= android.view.ViewRootImpl$8.onFrameDraw:13826 android.view.ThreadedRenderer$1.onFrameDraw:792 <bottom of call stack>
03-10 18:30:28.347 20216 20312 I ViewRootImpl@5fde030[SBrowserMainActivity]: Setting up sync and frameCommitCallback
03-10 18:30:28.378 20216 20304 I BLASTBufferQueue: [ViewRootImpl@5fde030[SBrowserMainActivity]#1](f:0,a:0,s:0) onFrameAvailable the first frame is available
03-10 18:30:28.379 20216 20304 I ViewRootImpl@5fde030[SBrowserMainActivity]: Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
03-10 18:30:28.379 20216 20216 I ViewRootImpl@5fde030[SBrowserMainActivity]: reportDrawFinished seqId=0
03-10 18:30:28.390 20216 20665 I Process : Sending signal. PID: 20216 SIG: 9
```

**Comment by JingMatrix** [comment]
It doesn't seem to be issue of `ChromeXt`.
Are you using other modules? If so, disable them.
And it seems that you know how to get `adb` logs, please try 
```
adb logcat -s ChromeXt AndroidRunTime LSPosed LSPatch
```

**Comment by ehfkwlfkwl** [comment]
I'm not using other modules
I'll think about it more

`
--------- beginning of main
03-10 18:38:49.569 24215 24215 I LSPatch : Use manager: false
03-10 18:38:49.570 24215 24215 I LSPatch : Signature bypass level: 0
03-10 18:38:49.570 24215 24215 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:38:49.580 24215 24215 I LSPatch : Load modules
03-10 18:38:49.647 24215 24215 I LSPatch : Modules initialized
03-10 18:38:49.648 24215 24215 I LSPatch : LSPatch bootstrap completed
03-10 18:38:49.690 24215 24215 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 18:45:15.671 26076 26076 I LSPatch : Use manager: false
03-10 18:45:15.671 26076 26076 I LSPatch : Signature bypass level: 0
03-10 18:45:15.671 26076 26076 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:45:15.686 26076 26076 I LSPatch : Load modules
03-10 18:45:15.770 26076 26076 I LSPatch : Modules initialized
03-10 18:45:15.770 26076 26076 I LSPatch : LSPatch bootstrap completed
03-10 18:45:15.813 26076 26076 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 18:45:16.059 26219 26219 I LSPatch : Use manager: false
03-10 18:45:16.059 26219 26219 I LSPatch : Signature bypass level: 0
03-10 18:45:16.060 26219 26219 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:45:16.073 26219 26219 I LSPatch : Load modules
03-10 18:45:16.170 26219 26219 I LSPatch : Modules initialized
03-10 18:45:16.170 26219 26219 I LSPatch : LSPatch bootstrap completed
03-10 18:45:16.856 26333 26333 I LSPatch : Use manager: false
03-10 18:45:16.856 26333 26333 I LSPatch : Signature bypass level: 0
03-10 18:45:16.857 26333 26333 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:45:16.874 26333 26333 I LSPatch : Load modules
03-10 18:45:16.953 26333 26333 I LSPatch : Modules initialized
03-10 18:45:16.953 26333 26333 I LSPatch : LSPatch bootstrap completed
03-10 18:45:17.016 26333 26333 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 18:45:17.354 26455 26455 I LSPatch : Use manager: false
03-10 18:45:17.355 26455 26455 I LSPatch : Signature bypass level: 0
03-10 18:45:17.355 26455 26455 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:45:17.396 26455 26455 I LSPatch : Load modules
03-10 18:45:17.581 26455 26455 I LSPatch : Modules initialized
03-10 18:45:17.582 26455 26455 I LSPatch : LSPatch bootstrap completed
03-10 18:45:47.816 26939 26939 I LSPatch : Use manager: false
03-10 18:45:47.816 26939 26939 I LSPatch : Signature bypass level: 0
03-10 18:45:47.816 26939 26939 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:45:47.826 26939 26939 I LSPatch : Load modules
03-10 18:45:47.902 26939 26939 I LSPatch : Modules initialized
03-10 18:45:47.902 26939 26939 I LSPatch : LSPatch bootstrap completed
03-10 18:45:47.944 26939 26939 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 18:45:48.549 27043 27043 I LSPatch : Use manager: false
03-10 18:45:48.549 27043 27043 I LSPatch : Signature bypass level: 0
03-10 18:45:48.549 27043 27043 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:45:48.566 27043 27043 I LSPatch : Load modules
03-10 18:45:48.657 27043 27043 I LSPatch : Modules initialized
03-10 18:45:48.657 27043 27043 I LSPatch : LSPatch bootstrap completed
03-10 18:45:58.541 27787 27787 I LSPatch : Use manager: false
03-10 18:45:58.541 27787 27787 I LSPatch : Signature bypass level: 0
03-10 18:45:58.541 27787 27787 I LSPatch : Extract original apk
03-10 18:45:58.680 27787 27787 I LSPatch : hooked app initialized: android.app.LoadedApk@297fb99
03-10 18:45:58.682 27787 27787 I LSPatch : Extract module apk: org.matrix.chromext
03-10 18:45:58.691 27787 27787 I LSPatch : Load modules
03-10 18:45:58.816 27787 27787 I LSPatch : Modules initialized
03-10 18:45:58.817 27787 27787 I LSPatch : LSPatch bootstrap completed
03-10 18:45:58.913 27787 27787 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 18:45:59.183 27922 27922 I LSPatch : Use manager: false
03-10 18:45:59.183 27922 27922 I LSPatch : Signature bypass level: 0
03-10 18:45:59.183 27922 27922 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:45:59.193 27922 27922 I LSPatch : Load modules
03-10 18:45:59.319 27922 27922 I LSPatch : Modules initialized
03-10 18:45:59.320 27922 27922 I LSPatch : LSPatch bootstrap completed
03-10 18:46:00.583 27922 27922 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 18:46:01.530 28274 28274 I LSPatch : Use manager: false
03-10 18:46:01.530 28274 28274 I LSPatch : Signature bypass level: 0
03-10 18:46:01.530 28274 28274 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:46:01.552 28274 28274 I LSPatch : Load modules
03-10 18:46:01.629 28274 28274 I LSPatch : Modules initialized
03-10 18:46:01.629 28274 28274 I LSPatch : LSPatch bootstrap completed
03-10 18:46:01.678 28274 28274 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 18:48:35.855 31041 31041 I LSPatch : Use manager: false
03-10 18:48:35.856 31041 31041 I LSPatch : Signature bypass level: 2
03-10 18:48:35.857 31041 31041 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:48:35.895 31041 31041 I LSPatch : Load modules
03-10 18:48:36.086 31041 31041 I LSPatch : Modules initialized
03-10 18:48:36.099 31041 31041 I LSPatch : LSPatch bootstrap completed
03-10 18:53:01.229  1766  1766 I LSPatch : Use manager: false
03-10 18:53:01.229  1766  1766 I LSPatch : Signature bypass level: 0
03-10 18:53:01.229  1766  1766 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:53:01.245  1766  1766 I LSPatch : Load modules
03-10 18:53:01.353  1766  1766 I LSPatch : Modules initialized
03-10 18:53:01.353  1766  1766 I LSPatch : LSPatch bootstrap completed
03-10 18:53:54.610  3260  3260 I LSPatch : Use manager: false
03-10 18:53:54.610  3260  3260 I LSPatch : Signature bypass level: 0
03-10 18:53:54.610  3260  3260 I LSPatch : Extract original apk
03-10 18:53:54.747  3260  3260 I LSPatch : hooked app initialized: android.app.LoadedApk@297fb99
03-10 18:53:54.750  3260  3260 I LSPatch : Extract module apk: org.matrix.chromext
03-10 18:53:54.758  3260  3260 I LSPatch : Load modules
03-10 18:53:54.885  3260  3260 I LSPatch : Modules initialized
03-10 18:53:54.885  3260  3260 I LSPatch : LSPatch bootstrap completed
03-10 18:53:54.981  3260  3260 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 18:53:55.259  3471  3471 I LSPatch : Use manager: false
03-10 18:53:55.259  3471  3471 I LSPatch : Signature bypass level: 0
03-10 18:53:55.259  3471  3471 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:53:55.268  3471  3471 I LSPatch : Load modules
03-10 18:53:55.393  3471  3471 I LSPatch : Modules initialized
03-10 18:53:55.393  3471  3471 I LSPatch : LSPatch bootstrap completed
03-10 18:54:41.184  3471  3471 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 18:54:41.433  3901  3901 I LSPatch : Use manager: false
03-10 18:54:41.433  3901  3901 I LSPatch : Signature bypass level: 0
03-10 18:54:41.433  3901  3901 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 18:54:41.443  3901  3901 I LSPatch : Load modules
03-10 18:54:41.510  3901  3901 I LSPatch : Modules initialized
03-10 18:54:41.510  3901  3901 I LSPatch : LSPatch bootstrap completed
03-10 19:00:11.262 31041 31041 I ChromeXt: Package: com.sec.android.app.sbrowser, v23.0.1.1
03-10 19:00:11.590  7420  7420 I LSPatch : Use manager: false
03-10 19:00:11.591  7420  7420 I LSPatch : Signature bypass level: 2
03-10 19:00:11.591  7420  7420 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 19:00:11.612  7420  7420 I LSPatch : Load modules
03-10 19:00:11.724  7420  7420 I LSPatch : Modules initialized
03-10 19:00:11.730  7420  7420 I LSPatch : LSPatch bootstrap completed
03-10 19:00:20.538  7664  7664 I LSPatch : Use manager: false
03-10 19:00:20.538  7664  7664 I LSPatch : Signature bypass level: 0
03-10 19:00:20.538  7664  7664 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 19:00:20.550  7664  7664 I LSPatch : Load modules
03-10 19:00:20.637  7664  7664 I LSPatch : Modules initialized
03-10 19:00:20.637  7664  7664 I LSPatch : LSPatch bootstrap completed
03-10 19:00:20.693  7664  7664 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 19:00:23.663  7825  7825 I LSPatch : Use manager: false
03-10 19:00:23.663  7825  7825 I LSPatch : Signature bypass level: 0
03-10 19:00:23.667  7825  7825 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 19:00:23.685  7825  7825 I LSPatch : Load modules
03-10 19:00:23.756  7825  7825 I LSPatch : Modules initialized
03-10 19:00:23.756  7825  7825 I LSPatch : LSPatch bootstrap completed
03-10 19:00:23.801  7825  7825 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 19:00:24.104  7955  7955 I LSPatch : Use manager: false
03-10 19:00:24.104  7955  7955 I LSPatch : Signature bypass level: 0
03-10 19:00:24.105  7955  7955 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 19:00:24.144  7955  7955 I LSPatch : Load modules
03-10 19:00:24.343  7955  7955 I LSPatch : Modules initialized
03-10 19:00:24.344  7955  7955 I LSPatch : LSPatch bootstrap completed
03-10 19:00:26.245  8189  8189 I LSPatch : Use manager: false
03-10 19:00:26.245  8189  8189 I LSPatch : Signature bypass level: 0
03-10 19:00:26.245  8189  8189 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 19:00:26.265  8189  8189 I LSPatch : Load modules
03-10 19:00:26.339  8189  8189 I LSPatch : Modules initialized
03-10 19:00:26.339  8189  8189 I LSPatch : LSPatch bootstrap completed
03-10 19:00:26.391  8189  8189 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-10 19:00:30.644  8334  8334 I LSPatch : Use manager: false
03-10 19:00:30.645  8334  8334 I LSPatch : Signature bypass level: 0
03-10 19:00:30.646  8334  8334 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-10 19:00:30.687  8334  8334 I LSPatch : Load modules
03-10 19:00:30.874  8334  8334 I LSPatch : Modules initialized
03-10 19:00:30.875  8334  8334 I LSPatch : LSPatch bootstrap completed
`

**Comment by JingMatrix** [comment]
Your provided log did not catch a crash, because no entry of `AndroidRuntime` appeared.
It was my mistake (a typo), a better logcat command should be
```
adb logcat -s ChromeXt AndroidRuntime LSPatch
```

**Comment by ehfkwlfkwl** [comment]
`
adb logcat -s ChromeXt AndroidRuntime LSPatch
`

`
03-11 02:21:59.066 28456 28456 I LSPatch : Use manager: false
03-11 02:21:59.066 28456 28456 I LSPatch : Signature bypass level: 2
03-11 02:21:59.066 28456 28456 I LSPatch : Extract original apk
03-11 02:21:59.395 28456 28456 I LSPatch : hooked app initialized: android.app.LoadedApk@297fb99
03-11 02:21:59.399 28456 28456 I LSPatch : Extract module apk: org.matrix.chromext
03-11 02:21:59.412 28456 28456 I LSPatch : Load modules
03-11 02:21:59.538 28456 28456 I LSPatch : Modules initialized
03-11 02:21:59.542 28456 28456 I LSPatch : LSPatch bootstrap completed
03-11 02:21:59.703 28456 28456 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-11 02:22:00.303 28456 28617 E AndroidRuntime: FATAL EXCEPTION: pool-9-thread-1
03-11 02:22:00.303 28456 28617 E AndroidRuntime: Process: com.sec.android.app.sbrowser.beta, PID: 28456
03-11 02:22:00.303 28456 28617 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=intellivoiceservice.intent.action.BIND_TRANSLATION pkg=com.samsung.android.intellivoiceservice }
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2203)
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at android.app.ContextImpl.bindService(ContextImpl.java:2060)
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at android.content.ContextWrapper.bindService(ContextWrapper.java:878)
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ConnectionManager.connectToService(Unknown Source:52)
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ConnectionManager.connect(Unknown Source:18)
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ServiceExecutor.connect(Unknown Source:19)
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ServiceExecutor.beforeExecute(Unknown Source:97)
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-11 02:22:00.303 28456 28617 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
03-11 02:22:00.558 28666 28666 I LSPatch : Use manager: false
03-11 02:22:00.558 28666 28666 I LSPatch : Signature bypass level: 2
03-11 02:22:00.559 28666 28666 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-11 02:22:00.573 28666 28666 I LSPatch : Load modules
03-11 02:22:00.690 28666 28666 I LSPatch : Modules initialized
03-11 02:22:00.694 28666 28666 I LSPatch : LSPatch bootstrap completed
03-11 02:22:16.541 28666 28666 I ChromeXt: Package: com.sec.android.app.sbrowser.beta, v25.0.0.20
03-11 02:22:16.949 28666 29238 E AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
03-11 02:22:16.949 28666 29238 E AndroidRuntime: Process: com.sec.android.app.sbrowser.beta, PID: 28666
03-11 02:22:16.949 28666 29238 E AndroidRuntime: java.lang.SecurityException: Not allowed to bind to service Intent { act=intellivoiceservice.intent.action.BIND_TRANSLATION pkg=com.samsung.android.intellivoiceservice }
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:2203)
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at android.app.ContextImpl.bindService(ContextImpl.java:2060)
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at android.content.ContextWrapper.bindService(ContextWrapper.java:878)
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ConnectionManager.connectToService(Unknown Source:52)
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ConnectionManager.connect(Unknown Source:18)
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ServiceExecutor.connect(Unknown Source:19)
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at com.samsung.android.sdk.scs.base.connection.ServiceExecutor.beforeExecute(Unknown Source:97)
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1143)
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
03-11 02:22:16.949 28666 29238 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1012)
03-11 02:22:17.956 29326 29326 I LSPatch : Use manager: false
03-11 02:22:17.956 29326 29326 I LSPatch : Signature bypass level: 2
03-11 02:22:17.959 29326 29326 I LSPatch : hooked app initialized: android.app.LoadedApk@e2b312
03-11 02:22:18.036 29326 29326 I LSPatch : Load modules
03-11 02:22:18.243 29326 29326 I LSPatch : Modules initialized
03-11 02:22:18.266 29326 29326 I LSPatch : LSPatch bootstrap completed
03-11 02:22:21.153 29326 29326 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
`

**Comment by JingMatrix** [comment]
I really have no idea what was happening.
Probably I cannot help since I don't have a Samsung device.

**Comment by ehfkwlfkwl** [comment]
I solved the problem by uninstalling com.samsung.android.intellivoiceservice

```
adb shell pm uninstall --user 0 com.samsung.android.intellivoiceservice
```

If I reinstall it, Samsung Internet crashes

**Comment by JingMatrix** [comment]
As given in the [doc of  Context class](https://developer.android.com/reference/android/content/Context#bindService(android.content.Intent,%20android.content.ServiceConnection,%20int)), the `SecurityException` is thrown if
```
If the caller does not have permission to access the service or the service cannot be found.
```

It might be that `LSPatch` changes the signature of the browser so that the permission is no longer not granted.
By contrast, the modified `AndroidManifest` file never removes permission declartions.

**Comment by JingMatrix** [comment]
The following lines are found in the `AndroidManifest` of `Samsung Intelligence Voice Services`.

```
<permission android:label="Translation Service Access Permission" android:name="com.samsung.android.intellivoiceservice.aitranslator.permission.BIND_TRANSLATION" android:protectionLevel="signatureOrSystem"/>
<permission android:label="Speech Recognition Service Bind Permission (Normal)" android:name="com.samsung.android.intellivoiceservice.ai.asr.permission.BIND_SPEECH_RECOGNITION_SERVICE" android:protectionLevel="normal"/>
<permission android:label="Speech Recognition Service Config Provider Permission (Normal)" android:name="com.samsung.android.intellivoiceservice.ai.asr.permission.SPEECH_RECOGNITION_SERVICE_CONFIG_PROVIDER" android:protectionLevel="normal"/>
<permission android:label="Speech Recognition Service Bind Permission" android:name="com.samsung.android.intellivoiceservice.ai.asr.permission.SYSTEM_BIND_SPEECH_RECOGNITION_SERVICE" android:protectionLevel="signatureOrSystem"/>
<permission android:label="Speech Recognition Service Config Provider Permission" android:name="com.samsung.android.intellivoiceservice.ai.asr.permission.SYSTEM_SPEECH_RECOGNITION_SERVICE_CONFIG_PROVIDER" android:protectionLevel="signatureOrSystem"/>
```

As said in the [docs of permissionLevel](https://developer.android.com/guide/topics/manifest/permission-element#plevel),
```
A permission that the system grants only to applications that are in a dedicated folder on the Android system image or that are signed with the same certificate as the application that declared the permission. Avoid using this option, as the "signature" protection level is sufficient for most needs and works regardless of where apps are installed.

The "signatureOrSystem" permission is used for certain special situations where multiple vendors have applications built into a system image and need to share specific features explicitly because they are being built together.
```
Hence, it is barely possible for LSPatch to bypass the given `protectionLevel` since signature is needed.
By contrast, `LSPosed` with root permission works fine (which is my case) since the app signature remains unchanged.
