### ISSUE TITLE
ChromeXt does not work on Samsung SM-G9500 with LSPosed v1.9.2

### ISSUE THREAD

**Issue by passcodex** [JingMatrix/ChromeXt#169]
LSPosed Information
**API version**
100

**Xposed API call protection**
Enabled

**Dex Optimizer Wrapper**
Unsupported (Android version unsatisfied)

**Framework version**
1.9.2 (7024)

**Manager package name**
com.android.shell

**System version**
9 (API 28)

**Device**
Samsung SM-G9500 

**System ABI**
arm64-v8a

**Browser(Installed from APK standalone installer)**
Package: com.sec.android.app.sbrowser, v21.0.3.6 From [APKMirror](https://www.apkmirror.com/apk/samsung-electronics-co-ltd/samsung-internet-for-android/samsung-internet-for-android-21-0-3-6-release/samsung-internet-browser-21-0-3-6-android-apk-download/#file)
Package: com.android.chrome, v98.0.4758.101 From [APKMirror](https://www.apkmirror.com/apk/google-inc/chrome/chrome-98-0-4758-101-release/google-chrome-fast-secure-98-0-4758-101-8-android-apk-download/)

**ChromeXt Version**
https://github.com/JingMatrix/ChromeXt/actions/runs/8951312334
![image](https://github.com/JingMatrix/ChromeXt/assets/11014056/2fe56e28-332c-448e-8d35-bff134f11252)

**Debug Info**
```
C:\adb logcat -s ChromeXt:D
--------- beginning of main
--------- beginning of system
05-21 16:23:12.763 18402 18402 I ChromeXt: Package: com.sec.android.app.sbrowser, v21.0.3.6
05-21 16:23:12.787 18402 18402 E ChromeXt:
05-21 16:23:12.787 18402 18402 E ChromeXt: java.lang.NoSuchMethodException
05-21 16:23:12.787 18402 18402 E ChromeXt:      at a.a.n(SourceFile:15)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at p.q.a(SourceFile:15)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at org.matrix.chromext.MainHook.b(SourceFile:11)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at n.q.c(SourceFile:902)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at n.q.b(SourceFile:40)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at s.a.afterHookedMethod(SourceFile:23)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at sEd.eoh.L.NNZ.JnriIwcH.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at J.callback(Unknown Source:292)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at LSPHooker_.constructor(Unknown Source:14)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at org.chromium.ui.base.ActivityWindowAndroid.<init>(ActivityWindowAndroid.java:5)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at org.chromium.ui.base.ActivityWindowAndroid.<init>(ActivityWindowAndroid.java:4)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at com.sec.terrace.TerraceActivity$2.<init>(TerraceActivity.java:3)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at com.sec.terrace.TerraceActivity.onCreate(TerraceActivity.java:39)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at com.sec.android.app.sbrowser.tab.TabActivity.onCreate(TabActivity.java:1)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at com.sec.android.app.sbrowser.SBrowserMainActivity.onCreate(SBrowserMainActivity.java:53)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.Activity.performCreate(Activity.java:7327)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.Activity.performCreate(Activity.java:7318)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.os.Handler.dispatchMessage(Handler.java:106)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.os.Looper.loop(Looper.java:214)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at android.app.ActivityThread.main(ActivityThread.java:7050)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at java.lang.reflect.Method.invoke(Native Method)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
05-21 16:23:12.787 18402 18402 E ChromeXt:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
05-21 16:28:29.069 20959 20959 I ChromeXt: Package: com.android.chrome, v98.0.4758.101
05-21 16:28:29.087 20959 20959 E ChromeXt:
05-21 16:28:29.087 20959 20959 E ChromeXt: java.lang.ExceptionInInitializerError
05-21 16:28:29.087 20959 20959 E ChromeXt:      at p.q.a(SourceFile:1)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at org.matrix.chromext.MainHook.b(SourceFile:11)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at n.q.c(SourceFile:902)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at n.q.b(SourceFile:40)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at s.a.afterHookedMethod(SourceFile:23)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at sEd.eoh.L.NNZ.JnriIwcH.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at J.callback(Unknown Source:292)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at LSPHooker_.constructor(Unknown Source:14)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at D6.<init>(chromium-Monochrome.aab-stable-475810123:8)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at D6.<init>(chromium-Monochrome.aab-stable-475810123:7)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at n40.<init>(chromium-Monochrome.aab-stable-475810123:3)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at org.chromium.chrome.browser.app.ChromeActivity.B0(chromium-Monochrome.aab-stable-475810123:5)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at zo.onCreate(chromium-Monochrome.aab-stable-475810123:26)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.Activity.performCreate(Activity.java:7327)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.Activity.performCreate(Activity.java:7318)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.os.Handler.dispatchMessage(Handler.java:106)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.os.Looper.loop(Looper.java:214)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at android.app.ActivityThread.main(ActivityThread.java:7050)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at java.lang.reflect.Method.invoke(Native Method)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
05-21 16:28:29.087 20959 20959 E ChromeXt:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
05-21 16:28:29.087 20959 20959 E ChromeXt: Caused by: java.lang.NullPointerException
05-21 16:28:29.087 20959 20959 E ChromeXt:      at q.h.<clinit>(SourceFile:270)
05-21 16:28:29.087 20959 20959 E ChromeXt:      ... 28 more
```

**Comment by JingMatrix** [comment]
Could you please update your Chrome and Samsung browsers?
`ChromeXt` should focus on supporting current versions of browsers instead of old ones.
